
# motd 3行目以降(最後の行)に挿入される値
values:
  - input: "%server_has_whitelist%"  # 入力される文字列 (PAPI可)
    pattern: "^yes$"  # 正規表現された条件 (省略可,PAPI可)
    output-true: "§cWHITELIST-ON"  # 条件に合うときの出力  (省略可,PAPI可)
    output-false: "§aWHITELIST-OFF"  # 条件に合わないときの出力  (省略可,PAPI可)

# 値同士を繋ぐ文字列
values-join: "\0"
